In [1]:
import numpy as np

In [7]:
sample = np.ndarray((2,3))

In [8]:
sample.shape

(2, 3)

In [9]:
sample.dtype

dtype('float64')

In [13]:
array = np.arange(32).reshape((8,4))
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [14]:
array[[1,3,5,7], [0,3,2,1]]

array([ 4, 15, 22, 29])

In [15]:
array[[1,3,5,7]][:, [0,3,2,1]]

array([[ 4,  7,  6,  5],
       [12, 15, 14, 13],
       [20, 23, 22, 21],
       [28, 31, 30, 29]])

In [16]:
array[np.ix_([1,3,5,7], [0,3,2,1])]

array([[ 4,  7,  6,  5],
       [12, 15, 14, 13],
       [20, 23, 22, 21],
       [28, 31, 30, 29]])

In [18]:
a, b = [1,2,3], [4,5,6]
x = zip(a,b)
print(x) # iterator pala si x

Actually alam ko na yung mga nilagay rito so wala akong masyadong matetest unless magsagot ako ng problems or magcheck ng documentation.