In [20]:
import torch
torch.__version__

'2.0.1+cu117'

## Tensors
Building blocks of PyTorch that can represent data in a numerical way.

In [21]:
# Scalars - is a single number and in tensor-speak it's a zero dimension tensor.
scalar = torch.tensor(7)
# scalar - prints tensor(7)
# scalar.ndim - prints 0
scalar.item()

7

In [16]:
# Vector - flexible one
vector = torch.tensor([7, 7])
vector.ndim # count the number of square brackets to identify dim

1

In [18]:
# Matrix - more flexible than vectors and has more dimensions
matrix = torch.tensor([[7,8],
                      [9,10]])
# matrix.ndim - prints 2
matrix.shape

torch.Size([2, 2])

In [22]:
# TENSOR - bigger MATRICES WITH MORE NUMBERS
tensor = torch.tensor([[1, 2, 3],
                      [1, 2, 3],
                      [1, 2, 3]])
tensor

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [23]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.7509, 0.4894, 0.7435, 0.2573],
         [0.9046, 0.6241, 0.8661, 0.0589],
         [0.7342, 0.0043, 0.5119, 0.8246]]),
 torch.float32)

In [24]:
zeros_tensor = torch.zeros(size=(3,4))
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
ones_tensor = torch.ones(size=(3,4))
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
# Creating a range and tensors like
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Getting information from tensors
We've already tackled `shape` and `dtype`. There's also `device` which tells where the tensor is stored on (GPU or CPU).

## Tensor operations
Operations work like Numpy arrays. (Vector addition, multiplication, etc.)

In [27]:
sample_tensor = torch.tensor([1, 2, 3])
sample_tensor+10

tensor([11, 12, 13])

In [28]:
sample_tensor = torch.tensor([1, 2, 3])
sample_tensor-5

tensor([-4, -3, -2])

In [29]:
sample_tensor = torch.tensor([1, 2, 3])
sample_tensor*10

tensor([10, 20, 30])

In [30]:
sample_tensor = torch.tensor([1, 2, 3])
sample_tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [32]:
# Matrix multiplication
sample_tensor2 = torch.tensor([3, 2, 1])
sample_tensor.matmul(sample_tensor2)

tensor(10)

In [33]:
# Element-wise matrix multiplication
sample_tensor * sample_tensor2

tensor([3, 4, 3])

In [35]:
# Tranpose using T
sample_tensor3 = torch.tensor([[1,2,3],
                              [3,2,1]])
sample_tensor3.T

tensor([[1, 3],
        [2, 2],
        [3, 1]])

## Feed forward test with nn.linear()

In [39]:
# Make the test reproducible
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                        out_features=6) # out_features = describes outer value
x = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[0.9332, 0.8805, 3.0149, 1.5545, 1.8186, 2.0634],
        [1.7186, 1.4009, 3.5818, 1.7408, 2.6017, 2.5123]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([2, 6])


## Aggregates

In [40]:
# Create a tensor
x = torch.arange(0, 100, 10)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [42]:
# Same can be done using torch methods
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [43]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0
