In [35]:
import torch
torch.__version__

'2.0.1+cpu'

## Tensors
Building blocks of PyTorch that can represent data in a numerical way.

In [36]:
# Scalars - is a single number and in tensor-speak it's a zero dimension tensor.
scalar = torch.tensor(7)
# scalar - prints tensor(7)
# scalar.ndim - prints 0
scalar.item()

7

In [37]:
# Vector - flexible one
vector = torch.tensor([7, 7])
vector.ndim # count the number of square brackets to identify dim

1

In [38]:
# Matrix - more flexible than vectors and has more dimensions
matrix = torch.tensor([[7,8],
                      [9,10]])
# matrix.ndim - prints 2
matrix.shape

torch.Size([2, 2])

In [39]:
# TENSOR - bigger MATRICES WITH MORE NUMBERS
tensor = torch.tensor([[1, 2, 3],
                      [1, 2, 3],
                      [1, 2, 3]])
tensor

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [40]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.2666, 0.6274, 0.2696, 0.4414],
         [0.2969, 0.8317, 0.1053, 0.2695],
         [0.3588, 0.1994, 0.5472, 0.0062]]),
 torch.float32)

In [41]:
zeros_tensor = torch.zeros(size=(3,4))
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [42]:
ones_tensor = torch.ones(size=(3,4))
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
# Creating a range and tensors like
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Getting information from tensors
We've already tackled `shape` and `dtype`. There's also `device` which tells where the tensor is stored on (GPU or CPU).

## Tensor operations
Operations work like Numpy arrays. (Vector addition, multiplication, etc.)

In [44]:
sample_tensor = torch.tensor([1, 2, 3])
sample_tensor+10

tensor([11, 12, 13])

In [45]:
sample_tensor = torch.tensor([1, 2, 3])
sample_tensor-5

tensor([-4, -3, -2])

In [46]:
sample_tensor = torch.tensor([1, 2, 3])
sample_tensor*10

tensor([10, 20, 30])

In [47]:
sample_tensor = torch.tensor([1, 2, 3])
sample_tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [48]:
# Matrix multiplication
sample_tensor2 = torch.tensor([3, 2, 1])
sample_tensor.matmul(sample_tensor2)

tensor(10)

In [49]:
# Element-wise matrix multiplication
sample_tensor * sample_tensor2

tensor([3, 4, 3])

In [50]:
# Tranpose using T
sample_tensor3 = torch.tensor([[1,2,3],
                              [3,2,1]])
sample_tensor3.T

tensor([[1, 3],
        [2, 2],
        [3, 1]])

## Feed forward test with nn.linear()

In [51]:
# Make the test reproducible
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                        out_features=6) # out_features = describes outer value
x = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


## Aggregates

In [52]:
# Create a tensor
x = torch.arange(0, 100, 10)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [53]:
# Same can be done using torch methods
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [54]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


## Changing data types

In [55]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [56]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

## Study Reshaping, stacking, squeezing and unsqueezing

In [61]:
x1 = torch.arange(1., 9.)
x1, x1.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [71]:
x_reshaped = x1.reshape(1, -1)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [66]:
x_view = x1.view(4,-1) # if we try to change the view, the original tensor also changes; view() views the the tensor in a new shape
x_view

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [69]:
x_stacked = torch.stack([x1, x1, x1, x1], dim=1) # dim = 0 stacks them as is while dim = 1 transposes x1 first then appends them to the left
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.]])

In [72]:
# Squeezing removes all dimensions that is equal to 1
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])
Previous shape: torch.Size([1, 8])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8.])
New shape: torch.Size([8])


In [73]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8.])
Previous shape: torch.Size([8])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])
New shape: torch.Size([1, 8])


In [74]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing is the same as Numpy's array indexing

In [76]:
x = torch.arange(1., 10.).reshape(1,3,3)
x

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [77]:
x[0]

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [78]:
x[0][0]

tensor([1., 2., 3.])

In [79]:
x[0][0][0]

tensor(1.)

In [80]:
x[:,0]

tensor([[1., 2., 3.]])

In [81]:
x[:,:,1]

tensor([[2., 5., 8.]])

## PyTorch tensors and Numpy
You can convert tensors to Numpy arrays and vice versa:
`torch.from_numpy()` (numpy array to tensor) and `torch.Tensor.numpy()` (tensor to numpy array)

In [84]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor
# Note that the datatype directs to float64 but can be swapped into float32 if you use `.type(torch.float32)`

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [85]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility
Experiments should be reproducible for verification purposes.

In [88]:
torch.manual_seed(seed=42) # Only applies to the next randomized variable
x = torch.rand(size=(4,2))
torch.manual_seed(seed=42) # If you comment this line out, the output will print False
y = torch.rand(size=(4,2))
x == y

tensor([[True, True],
        [True, True],
        [True, True],
        [True, True]])

## Exercise time