In [20]:
import torch
torch.__version__

'2.0.1+cu117'

## Tensors
Building blocks of PyTorch that can represent data in a numerical way.

In [21]:
# Scalars - is a single number and in tensor-speak it's a zero dimension tensor.
scalar = torch.tensor(7)
# scalar - prints tensor(7)
# scalar.ndim - prints 0
scalar.item()

7

In [16]:
# Vector - flexible one
vector = torch.tensor([7, 7])
vector.ndim # count the number of square brackets to identify dim

1

In [18]:
# Matrix - more flexible than vectors and has more dimensions
matrix = torch.tensor([[7,8],
                      [9,10]])
# matrix.ndim - prints 2
matrix.shape

torch.Size([2, 2])

In [22]:
# TENSOR - bigger MATRICES WITH MORE NUMBERS
tensor = torch.tensor([[1, 2, 3],
                      [1, 2, 3],
                      [1, 2, 3]])
tensor

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [23]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.7509, 0.4894, 0.7435, 0.2573],
         [0.9046, 0.6241, 0.8661, 0.0589],
         [0.7342, 0.0043, 0.5119, 0.8246]]),
 torch.float32)

In [24]:
zeros_tensor = torch.zeros(size=(3,4))
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
ones_tensor = torch.ones(size=(3,4))
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
# Creating a range and tensors like
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Getting information from tensors
We've already tackled `shape` and `dtype`. There's also `device` which tells where the tensor is stored on (GPU or CPU).