In [1]:
import torch

In [3]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [5]:
x.numel()

12

In [6]:
x.shape

torch.Size([12])

In [10]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

The same `reshape` method can be done by using inference.

In [11]:
X = x.reshape(-1, 4) # -1 infers the remaining size of the component, the same output applies to x.reshape(3, -1)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

## Fill methods

In [13]:
torch.zeros((1, 2, 3))

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [14]:
torch.ones((1, 2, 3))

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [15]:
torch.randn((3, 4))

tensor([[-1.1168,  0.3566, -2.7569,  1.3296],
        [-1.2352,  1.7406, -0.3900, -0.0307],
        [-1.2727,  0.5616,  1.2606,  0.1915]])

In [16]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## Indexing and Slicing

In [17]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [18]:
X[1,2]

tensor(6.)

In [19]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## Operations

In [20]:
torch.exp(x) # applies the unary operator e^x

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

We can also do addition and subtraction of tensors.

In [21]:
x = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
y = torch.tensor([5, 6, 7, 8], dtype=torch.float32)
x+y, x-y, x*y, x/y

(tensor([ 6.,  8., 10., 12.]),
 tensor([-4., -4., -4., -4.]),
 tensor([ 5., 12., 21., 32.]),
 tensor([0.2000, 0.3333, 0.4286, 0.5000]))

We can also perform concatenations.

In [23]:
x = torch.arange(12, dtype=torch.float32).reshape(3,4)
y = torch.tensor([[13, 12, 1, 1], [14, 5, 5, 7], [16, 32, 1, 8]])
torch.cat((x, y), dim=0), torch.cat((x, y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [13., 12.,  1.,  1.],
         [14.,  5.,  5.,  7.],
         [16., 32.,  1.,  8.]]),
 tensor([[ 0.,  1.,  2.,  3., 13., 12.,  1.,  1.],
         [ 4.,  5.,  6.,  7., 14.,  5.,  5.,  7.],
         [ 8.,  9., 10., 11., 16., 32.,  1.,  8.]]))

## Broadcasting

The same broadcasting technique is used by `torch` as to `numpy` when it comes to tensors with different shapes.

In [24]:
x = torch.tensor([[1], [2], [3]])
y = torch.tensor([0, 1])
x, y

(tensor([[1],
         [2],
         [3]]),
 tensor([0, 1]))

In [26]:
x+y

tensor([[1, 2],
        [2, 3],
        [3, 4]])

As you can see, the values for `y` is broadcasted to create a 3x2 tensor while `x` rows are broadcasted row-wise to create a 3x2 tensor.