In [1]:
import torch

In [3]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [5]:
x.numel()

12

In [6]:
x.shape

torch.Size([12])

In [10]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

The same `reshape` method can be done by using inference.

In [11]:
X = x.reshape(-1, 4) # -1 infers the remaining size of the component, the same output applies to x.reshape(3, -1)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

## Fill methods

In [13]:
torch.zeros((1, 2, 3))

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [14]:
torch.ones((1, 2, 3))

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [15]:
torch.randn((3, 4))

tensor([[-1.1168,  0.3566, -2.7569,  1.3296],
        [-1.2352,  1.7406, -0.3900, -0.0307],
        [-1.2727,  0.5616,  1.2606,  0.1915]])

In [16]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## Indexing and Slicing

In [17]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [18]:
X[1,2]

tensor(6.)

In [19]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## Operations

In [20]:
torch.exp(x) # applies the unary operator e^x

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

We can also do addition and subtraction of tensors.

In [21]:
x = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
y = torch.tensor([5, 6, 7, 8], dtype=torch.float32)
x+y, x-y, x*y, x/y

(tensor([ 6.,  8., 10., 12.]),
 tensor([-4., -4., -4., -4.]),
 tensor([ 5., 12., 21., 32.]),
 tensor([0.2000, 0.3333, 0.4286, 0.5000]))

We can also perform concatenations.

In [23]:
x = torch.arange(12, dtype=torch.float32).reshape(3,4)
y = torch.tensor([[13, 12, 1, 1], [14, 5, 5, 7], [16, 32, 1, 8]])
torch.cat((x, y), dim=0), torch.cat((x, y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [13., 12.,  1.,  1.],
         [14.,  5.,  5.,  7.],
         [16., 32.,  1.,  8.]]),
 tensor([[ 0.,  1.,  2.,  3., 13., 12.,  1.,  1.],
         [ 4.,  5.,  6.,  7., 14.,  5.,  5.,  7.],
         [ 8.,  9., 10., 11., 16., 32.,  1.,  8.]]))

## Broadcasting

The same broadcasting technique is used by `torch` as to `numpy` when it comes to tensors with different shapes.

In [24]:
x = torch.tensor([[1], [2], [3]])
y = torch.tensor([0, 1])
x, y

(tensor([[1],
         [2],
         [3]]),
 tensor([0, 1]))

In [26]:
x+y

tensor([[1, 2],
        [2, 3],
        [3, 4]])

As you can see, the values for `y` is broadcasted to create a 3x2 tensor while `x` rows are broadcasted row-wise to create a 3x2 tensor.

Good source:
https://stackoverflow.com/questions/51371070/how-does-pytorch-broadcasting-work

There are instances where broadcasting won't work.

## Saving Memory

Try to perform in-place operations when dealing with computations to avoid new memory allocation.

In [27]:
before = id(x)
x = x+y
id(x) == before

False

In [28]:
before = id(x)
x[:] = x+y
id(x) == before

True

In [29]:
before = id(x)
x += y
id(x) == before

True

## Exercises

1. Run the code in this section. Change the conditional statement X == Y to X < Y or X > Y, and then see what kind of tensor you can get.

In [30]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X < Y, X > Y

(tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

2. Replace the two tensors that operate by element in the broadcasting mechanism with other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?

In [39]:
a = torch.arange(12).reshape((6, 1, 2))
b = torch.arange(3).reshape((3, 1))
a, b

(tensor([[[ 0,  1]],
 
         [[ 2,  3]],
 
         [[ 4,  5]],
 
         [[ 6,  7]],
 
         [[ 8,  9]],
 
         [[10, 11]]]),
 tensor([[0],
         [1],
         [2]]))

In [40]:
a+b

tensor([[[ 0,  1],
         [ 1,  2],
         [ 2,  3]],

        [[ 2,  3],
         [ 3,  4],
         [ 4,  5]],

        [[ 4,  5],
         [ 5,  6],
         [ 6,  7]],

        [[ 6,  7],
         [ 7,  8],
         [ 8,  9]],

        [[ 8,  9],
         [ 9, 10],
         [10, 11]],

        [[10, 11],
         [11, 12],
         [12, 13]]])