In [1]:
import torch

In [3]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [5]:
x.numel()

12

In [6]:
x.shape

torch.Size([12])

In [10]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

The same `reshape` method can be done by using inference.

In [11]:
X = x.reshape(-1, 4) # -1 infers the remaining size of the component, the same output applies to x.reshape(3, -1)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

## Fill methods

In [13]:
torch.zeros((1, 2, 3))

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [14]:
torch.ones((1, 2, 3))

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [15]:
torch.randn((3, 4))

tensor([[-1.1168,  0.3566, -2.7569,  1.3296],
        [-1.2352,  1.7406, -0.3900, -0.0307],
        [-1.2727,  0.5616,  1.2606,  0.1915]])