In [1]:
import torch

In [2]:
A = torch.arange(12, dtype=torch.float32)
B = A.clone() # copy A to B
A, A+B

(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 tensor([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22.]))

In [3]:
A*B # A*B is element-wise multiplication

tensor([  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100., 121.])

What if magkaiba sila ng size?

In [8]:
A = torch.arange(12, dtype=torch.float32)
B = torch.arange(2, dtype=torch.float32)
A*B

RuntimeError: The size of tensor a (12) must match the size of tensor b (2) at non-singleton dimension 0

Seems like there's no broadcasting applied on Hadamard products. Note that broadcasting is sometimes a bad idea due to inefficient memory allocation.

Note on views and copies: Views can be made through basic indexing (bale kung may ginawa kang modifications dun sa first, makikita yung changes dun sa view) and copies can be made through advanced indexing.

## Reduction

In [12]:
A = torch.tensor(
    [
        [
            [
                [1, 2, 3]
            ],
        ],
        [
            [
                [1, 2, 3]
            ],
        ],
        [
            [
                [1, 2, 3]
            ],
        ],
    ]
)
A.sum(axis=1)

tensor([[[1, 2, 3]],

        [[1, 2, 3]],

        [[1, 2, 3]]])

That clears it. `sum` method reduction is done through the rows and columns of each inner matrices/vectors.

There's another method called `cumsum` that takes the cumulative sum of the tensor on its respective dimension.

## Exercises

1. Prove that the transpose of the transpose of a matrix is the matrix itself 

2. Given two matrices A
 andB
, show that sum and transposition comme.te

In [14]:
X = torch.arange(24, dtype=torch.float32).reshape((2,3,4))
X

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [18]:
X.sum(axis=0), X.sum(axis=0).shape

(tensor([[12., 14., 16., 18.],
         [20., 22., 24., 26.],
         [28., 30., 32., 34.]]),
 torch.Size([3, 4]))

In [19]:
X.sum(axis=1), X.sum(axis=1).shape

(tensor([[12., 15., 18., 21.],
         [48., 51., 54., 57.]]),
 torch.Size([2, 4]))

In [20]:
X.sum(axis=2), X.sum(axis=2).shape

(tensor([[ 6., 22., 38.],
         [54., 70., 86.]]),
 torch.Size([2, 3]))

Note: You can also get the sum for higher order axes.