In [2]:
import torch
print(torch.__version__)

2.1.0+cu121


In [3]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
# 2D tensor - has magnitude and direction
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
# count number of square brackets
vector.ndim

1

In [9]:
MATRIX = torch.tensor([[7,8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 6]])

In [18]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9859, 0.3701, 0.8395, 0.2724],
        [0.2454, 0.3405, 0.2300, 0.5517],
        [0.6114, 0.5850, 0.0376, 0.8694]])

In [19]:
random_tensor.ndim

2

In [20]:
random_tensor.shape

torch.Size([3, 4])

In [21]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [22]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

In [26]:
one_to_nine = torch.arange(start=1,end=11,step=2)
one_to_nine

tensor([1, 3, 5, 7, 9])

In [27]:
one_to_nine.shape

torch.Size([5])

In [28]:
ten_zeros = torch.zeros_like(one_to_nine)
ten_zeros

tensor([0, 0, 0, 0, 0])

In [29]:
ten_ones = torch.ones_like(one_to_nine)
ten_ones

tensor([1, 1, 1, 1, 1])

In [30]:
float_32_tensor = torch.tensor(
    [3,6,9],
    dtype = None,
    device = None,
    requires_grad = False
)
float_32_tensor

tensor([3, 6, 9])

In [31]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [32]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor*float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [33]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4333, 0.0033, 0.5538, 0.8073],
        [0.5380, 0.3174, 0.8540, 0.3025],
        [0.0261, 0.9144, 0.5964, 0.6669]])

In [34]:
some_tensor.dtype

torch.float32

In [35]:
some_tensor.shape

torch.Size([3, 4])

In [36]:
some_tensor.device

device(type='cpu')

In [37]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [38]:
tensor*10

tensor([10, 20, 30])

In [39]:
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [40]:
torch.matmul(tensor, tensor)

tensor(14)

In [41]:
tensor.shape

torch.Size([3])

In [42]:
torch.matmul(torch.rand(size=(3,3,2)), torch.rand(size=(3,2,3))).shape

torch.Size([3, 3, 3])

In [43]:
torch.matmul(torch.rand(size=(1,3,3, 4)), torch.rand(size=(4,3,4,4))).shape

torch.Size([4, 3, 3, 4])

Some tests above:
```python
(a,b,c,d) @ (e,f,g,h) => (e,b,c,h)
(a,b,c) @ (d,e,f) => (d,b,f)
```

In [44]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[2,4],
                        [6,8],
                        [10,12]])
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [45]:
tensor_B.T.shape

torch.Size([2, 3])

In [46]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 10,  22,  34],
        [ 22,  50,  78],
        [ 34,  78, 122]])

In [47]:
torch.mm(tensor_A.T, tensor_B)

tensor([[ 70,  88],
        [ 88, 112]])

In [48]:
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

### Reshaping Tensors

In [49]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

### Change the View

In [50]:
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [51]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

### Stack tensors on top of each other

In [52]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [53]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

Try higher dimensions. Also try hstack and vstack.

### Squeeze and Unsqueeze

In [54]:
x_squeeze = x.squeeze()
x_squeeze

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
x.squeeze().shape

torch.Size([9])

Squeeze removes all 1 dimensions.

Unsqueeze adds a single dimension to a target tensor at a specific dim.

In [56]:
x.unsqueeze(dim=1), x.unsqueeze(dim=1).shape

(tensor([[5],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [57]:
x_orig = torch.rand(size=(224,224,3))
torch.permute(x_orig, (2,0,1)).shape

torch.Size([3, 224, 224])

In [58]:
x = torch.arange(1, 10).reshape(1,3,3)

In [59]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [60]:
x[0, :, 2]

tensor([3, 6, 9])

### Reproducibility

Pseudo-randomness

In [64]:
torch.manual_seed(1337)

In [65]:
torch.rand(3,3)

tensor([[0.0783, 0.4956, 0.6231],
        [0.4224, 0.2004, 0.0287],
        [0.5851, 0.6967, 0.1761]])

In [66]:
torch.manual_seed(1337)

In [67]:
torch.rand(3,3)

tensor([[0.0783, 0.4956, 0.6231],
        [0.4224, 0.2004, 0.0287],
        [0.5851, 0.6967, 0.1761]])

Take note of reproducibility in PyTorch.

### Accessing a GPU

In [68]:
torch.cuda.is_available()

True

In [69]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [70]:
# Count the number of devices
torch.cuda.device_count()

1

In [71]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [73]:
tensor = torch.tensor([1,2,3], device=device)
print(tensor, tensor.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


### Putting tensors on the GPU and back to the CPU

In [74]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [75]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)