In [1]:
import torch
print(torch.__version__)

2.1.0+cu121


In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [7]:
# 2D tensor - has magnitude and direction
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
# count number of square brackets
vector.ndim

1

In [10]:
MATRIX = torch.tensor([[7,8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 6]])

In [19]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4853, 0.9184, 0.9223, 0.5090],
        [0.9548, 0.1578, 0.6601, 0.6911],
        [0.8528, 0.2622, 0.4475, 0.0187]])

In [20]:
random_tensor.ndim

2

In [21]:
random_tensor.shape

torch.Size([3, 4])

In [22]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [23]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

In [30]:
one_to_nine = torch.arange(start=1,end=11,step=2)
one_to_nine

tensor([1, 3, 5, 7, 9])

In [31]:
one_to_nine.shape

torch.Size([5])

In [33]:
ten_zeros = torch.zeros_like(one_to_nine)
ten_zeros

tensor([0, 0, 0, 0, 0])

In [35]:
ten_ones = torch.ones_like(one_to_nine)
ten_ones

tensor([1, 1, 1, 1, 1])

In [44]:
float_32_tensor = torch.tensor(
    [3,6,9],
    dtype = None,
    device = None,
    requires_grad = False
)
float_32_tensor

tensor([3, 6, 9])

In [45]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [46]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor*float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [47]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2281, 0.4908, 0.2256, 0.1003],
        [0.5461, 0.1726, 0.9252, 0.6587],
        [0.8943, 0.3044, 0.8225, 0.6046]])

In [48]:
some_tensor.dtype

torch.float32

In [49]:
some_tensor.shape

torch.Size([3, 4])

In [50]:
some_tensor.device

device(type='cpu')

In [51]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [52]:
tensor*10

tensor([10, 20, 30])

In [54]:
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [55]:
torch.matmul(tensor, tensor)

tensor(14)

In [56]:
tensor.shape

torch.Size([3])

In [60]:
torch.matmul(torch.rand(size=(3,3,2)), torch.rand(size=(3,2,3))).shape

torch.Size([3, 3, 3])

In [69]:
torch.matmul(torch.rand(size=(1,3,3, 4)), torch.rand(size=(4,3,4,4))).shape

torch.Size([4, 3, 3, 4])

Some tests above:
```python
(a,b,c,d) @ (e,f,g,h) => (e,b,c,h)
(a,b,c) @ (d,e,f) => (d,b,f)
```

In [71]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[2,4],
                        [6,8],
                        [10,12]])
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [72]:
tensor_B.T.shape

torch.Size([2, 3])

In [73]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 10,  22,  34],
        [ 22,  50,  78],
        [ 34,  78, 122]])

In [74]:
torch.mm(tensor_A.T, tensor_B)

tensor([[ 70,  88],
        [ 88, 112]])

In [75]:
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

### Reshaping Tensors

In [76]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

### Change the View

In [77]:
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [78]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))